apiVersion: apps/v1
kind: Deployment
metadata:
  name: g3-user
  namespace: namespace-g3
spec:
  selector:
    matchLabels:
      app: g3-user
  template:
    metadata:
      labels:
        app: g3-user
    spec:
      containers:
        - name: g3-user
          image: carolamaral/user-ilab-g3:latest
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: g3-configmap-user
                  key: DB_USERNAME
            - name: DB_URL_USER
              valueFrom:
                configMapKeyRef:
                  name: g3-configmap-user
                  key: DB_URL_USER
            - name: API_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: g3-configmap-user
                  key: API_AUTH_URL
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret-user-g3
                  key: DB_PASSWORD
          resources:
            limits:
              memory: "6Gi"
              cpu: "1"
          ports:
            - containerPort: 8082
